# Generated by Django 5.2.7 on 2025-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
