# Generated by Django 5.2.7 on 2025-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_alter_queue_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
