# Generated by Django 5.2.7 on 2025-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queue", "0003_alter_queue_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="queue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
