# Generated by Django 5.2.7 on 2025-10-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0004_queue_updated_at_alter_queue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='page_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
