# Generated by Django 5.2.7 on 2025-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0005_queue_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='print_mode',
            field=models.CharField(choices=[('single-sided', 'Single Sided'), ('double-sided', 'Double Sided')], default='single-sided', max_length=20),
        ),
    ]
