# Generated by Django 5.2.7 on 2025-11-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_rename_model_printers_name_printers_image_and_more'),
        ('queue', '0006_queue_print_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='printer_arrangement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.printerarrangements'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='page_count',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
