# Generated by Django 5.2.7 on 2025-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
