# Generated by Django 5.2.7 on 2025-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printers',
            name='charge',
        ),
        migrations.AddField(
            model_name='printers',
            name='duplex_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='printers',
            name='simplex_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
