# Generated by Django 5.2.7 on 2025-11-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_remove_printers_charge_printers_duplex_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printers',
            old_name='model',
            new_name='name',
        ),
        migrations.AddField(
            model_name='printers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='printers/'),
        ),
        migrations.AddField(
            model_name='printers',
            name='is_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printers',
            name='duplex_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printers',
            name='simplex_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PrinterArrangements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bw_printer', to='printers.printers')),
                ('color_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_printer', to='printers.printers')),
            ],
        ),
    ]
