# Generated by Django 5.2.7 on 2025-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_rename_model_printers_name_printers_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerarrangements',
            name='decomissioned',
            field=models.BooleanField(default=False),
        ),
    ]
