# Generated by Django 5.2.7 on 2025-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_printerarrangements_decomissioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='decomissioned',
            field=models.BooleanField(default=False),
        ),
    ]
